### PR TITLE
Fix for linux installation

### PR DESCRIPTION
**Pull request by mithusingh32**
- Updated numpy version to 1.24 or higher
- Removed Dora references
- Update README

### CODE REVIEW

**Comment by ChrisTG742** [comment]
@mithusingh32 did you test that updating numpy does not cause incompatibilites? There was/is some problems with librosa and numpy: https://github.com/Anjok07/ultimatevocalremovergui/issues/1016
Or did you update librosa aswell?

**Comment by mithusingh32** [comment]
I did some initially testing w/ demucs v4 htddemucs_ft with all default parameters and it worked. 
I will try perform more testing with other models + parameters. 

GPU: RTX 3070ti 8GB

**Comment by boredofnames** [comment]
You're assuming the shell with "./venv/bin/activate". This won't run under fish, for example.

**Comment by shervinemami** [comment]
Hi @mithusingh32 , I tried your Linux fix and it worked for me on Kubuntu 24.04. I tested with htdemucs_ft model on GPU as well as MDXNet using kuielab model on GPU. I had to rollback to using the older Python 3.11 instead of Python 3.12 that my system comes with.

I recommend adding this info to the Linux installation README so that all users can use the same Python version no matter their system comes with:

```
# Install UVR5 into a Python 3.11 venv (not virtualenv):
sudo add-apt-repository ppa:deadsnakes/ppa   # Access many Python versions
sudo apt update         # Allow installing many Python versions
sudo apt install python3.11        # Install Python 3.11
sudo apt install python3.11-venv   # So you can create venv virtual environments
sudo apt install python3.11-dev    # So you can build your own python packages, instead of only downloading them off the web
sudo apt install python3.11-tk     # So UVR can display graphics
python3.11 -m venv py3.11_UVR5.venv    # Create a new venv using Python 3.11
source py3.11_UVR5.venv/bin/activate
pip3 install --upgrade pip wheel   # Install or update the pip & wheel versions that are inside the venv
SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True pip3 install -r requirements.txt

# Run UVR5 in the Python virtual environment:
source py3.11_UVR5.venv/bin/activate
python3 UVR.py
```

**Review by Anjok07 — APPROVED** [review]

**Comment by GHDaddy** [comment]
> Hi @mithusingh32 , I tried your Linux fix and it worked for me on Kubuntu 24.04. I tested with htdemucs_ft model on GPU as well as MDXNet using kuielab model on GPU. I had to rollback to using the older Python 3.11 instead of Python 3.12 that my system comes with.
> 
> I recommend adding this info to the Linux installation README so that all users can use the same Python version no matter their system comes with:
> 
> ```
> # Install UVR5 into a Python 3.11 venv (not virtualenv):
> sudo add-apt-repository ppa:deadsnakes/ppa   # Access many Python versions
> sudo apt update         # Allow installing many Python versions
> sudo apt install python3.11        # Install Python 3.11
> sudo apt install python3.11-venv   # So you can create venv virtual environments
> sudo apt install python3.11-dev    # So you can build your own python packages, instead of only downloading them off the web
> sudo apt install python3.11-tk     # So UVR can display graphics
> python3.11 -m venv py3.11_UVR5.venv    # Create a new venv using Python 3.11
> source py3.11_UVR5.venv/bin/activate
> pip3 install --upgrade pip wheel   # Install or update the pip & wheel versions that are inside the venv
> SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True pip3 install -r requirements.txt
> 
> # Run UVR5 in the Python virtual environment:
> source py3.11_UVR5.venv/bin/activate
> python3 UVR.py
> ```

Dude idk what changed between my install and this, but doing this in a fresh venv worked. You saved me hours of ripping my hair out

**Comment by shervinemami** [comment]
> Dude idk what changed between my install and this, but doing this in a fresh venv worked. You saved me hours of ripping my hair out

I'm glad to hear!

**Pull request closed without merging**
